export * from './lab-base.service';
export * from './lab-categoria.service';
export * from './lab-ubicacion.service';
export * from './lab-area.service';
export * from './lab-almacenamiento.service';
export * from './lab-estado.service';
export * from './lab-insumo.service';
export * from './lab-movimiento.service';
export * from './lab-dashboard.service';
